version: '3.8'

services:
  cda:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:h2:mem:cdaDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.h2.Driver"
      SPRING_DATASOURCE_USERNAME: "test"
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.H2Dialect"
      SPRING_H2_CONSOLE_ENABLED: "true"
